#!/usr/bin/env bash

# Scheduled update/check runs: `deploy.sh schedule` writes a systemd
# service+timer pair (or a /etc/cron.d entry on non-systemd systems) that
# invokes the runner script; `deploy.sh unschedule` removes both. The runner
# takes the same manager lock as interactive batches, so scheduled and manual
# runs can never overlap, and reports its result through notify_send.
#
# Config lives in /etc/deploy-schedule.conf (root:600):
#   SCHEDULE_ENABLED=true|false
#   SCHEDULE_MODE=update-all|check-only
#   SCHEDULE_ON_CALENDAR=  systemd OnCalendar spec (default daily 04:30)
#   SCHEDULE_INCLUDE=      optional --include list passed to the batch command

SCHEDULE_CONF_FILE="${SCHEDULE_CONF_FILE:-/etc/deploy-schedule.conf}"
DEPLOY_SCHEDULE_SERVICE="${DEPLOY_SCHEDULE_SERVICE:-deploy-scripts-batch}"
DEPLOY_SCHEDULE_CRON_FILE="${DEPLOY_SCHEDULE_CRON_FILE:-/etc/cron.d/deploy-scripts-batch}"
DEPLOY_SCHEDULE_RUNNER="${DEPLOY_SCHEDULE_RUNNER:-/usr/local/bin/deploy-scripts-batch-runner}"

schedule_load_config() {
  local conf_file="$SCHEDULE_CONF_FILE"
  SCHEDULE_ENABLED=false SCHEDULE_MODE="update-all" SCHEDULE_ON_CALENDAR="" SCHEDULE_INCLUDE=""
  [[ -f "$conf_file" ]] || return 0
  local line key value
  while IFS= read -r line; do
    [[ "$line" =~ ^[A-Z_]+= ]] || continue
    key="${line%%=*}"
    value="${line#*=}"
    value="${value%\"}"
    value="${value#\"}"
    case "$key" in
      SCHEDULE_ENABLED|SCHEDULE_MODE|SCHEDULE_ON_CALENDAR|SCHEDULE_INCLUDE)
        printf -v "$key" '%s' "$value"
        ;;
    esac
  done < "$conf_file"
}

# The script invoked by systemd/cron. Takes the manager lock (fd8, shared
# with interactive batches), runs the configured batch, and lets the batch's
# own notification report the outcome. DEPLOY_NOTIFY_SUPPRESS is NOT set —
# scheduled runs are exactly when notifications matter most.
schedule_write_runner() {
  local runner="$DEPLOY_SCHEDULE_RUNNER"
  local root_dir_literal
  printf -v root_dir_literal '%q' "$DEPLOY_ROOT_DIR"
  if ! atomic_write_file "$runner" 750 <<RUNNER
#!/bin/bash
# Auto-generated by deploy.sh schedule. Do not edit manually.
set -euo pipefail
umask 077
exec bash ${root_dir_literal}/deploy.sh schedule-run
RUNNER
  then
    return 1
  fi
}

# Internal action executed by the runner. Reuses the manager lock so a
# concurrent interactive update-all/backup-all makes this run skip cleanly.
schedule_run_main() {
  require_root "schedule-run"
  schedule_load_config
  [[ "${SCHEDULE_ENABLED,,}" == true ]] || { echo "scheduled batch disabled; nothing to do." >&2; return 0; }
  local include_args=()
  if [[ -n "${SCHEDULE_INCLUDE:-}" ]]; then
    read -r -a include_args <<< "--include $SCHEDULE_INCLUDE"
  fi
  case "${SCHEDULE_MODE:-update-all}" in
    check-only)
      exec bash "$DEPLOY_ROOT_DIR/deploy.sh check-update" "${include_args[@]+"${include_args[@]}"}"
      ;;
    update-all)
      exec bash "$DEPLOY_ROOT_DIR/deploy.sh update-all" "${include_args[@]+"${include_args[@]}"}"
      ;;
    *)
      echo "unknown schedule mode: $SCHEDULE_MODE" >&2
      return 2
      ;;
  esac
}

# Write or refresh the scheduling units. Prefers systemd timers; falls back
# to /etc/cron.d where systemd is unavailable.
schedule_apply() {
  local calendar="$1"
  if command -v systemctl >/dev/null 2>&1 && systemctl is-system-running >/dev/null 2>&1; then
    local service_file="/etc/systemd/system/${DEPLOY_SCHEDULE_SERVICE}.service"
    local timer_file="/etc/systemd/system/${DEPLOY_SCHEDULE_SERVICE}.timer"
    atomic_write_file "$service_file" 644 <<SERVICE \
      || return 1
[Unit]
Description=deploy-scripts scheduled batch (update-all / check-update)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=${DEPLOY_SCHEDULE_RUNNER}
SERVICE
    atomic_write_file "$timer_file" 644 <<TIMER || return 1
[Unit]
Description=Run deploy-scripts scheduled batch

[Timer]
OnCalendar=${calendar}
Persistent=true

[Install]
WantedBy=timers.target
TIMER
    systemctl daemon-reload || return 1
    systemctl enable --now "${DEPLOY_SCHEDULE_SERVICE}.timer" >/dev/null 2>&1 || return 1
  else
    local cron_spec="${calendar}"
    # Convert the common daily "HH:MM" systemd form to cron; anything more
    # exotic must already be a valid 5-field crontab expression.
    if [[ "$calendar" =~ ^([0-9]+):([0-9]+)$ ]]; then
      cron_spec="$((10#${BASH_REMATCH[2]})) $((10#${BASH_REMATCH[1]})) * * *"
    fi
    if ! [[ "$cron_spec" =~ ^[0-9*,-/]+[[:space:]]+[0-9*,-/]+[[:space:]]+[0-9*,-/]+[[:space:]]+[0-9*,-/]+[[:space:]]+[0-9*,-/]+$ ]]; then
      echo "Invalid schedule specification: $calendar" >&2
      return 2
    fi
    atomic_write_file "$DEPLOY_SCHEDULE_CRON_FILE" 644 <<CRON || return 1
# Auto-generated by deploy.sh schedule. Do not edit manually.
${cron_spec} root ${DEPLOY_SCHEDULE_RUNNER}
CRON
    chmod 644 "$DEPLOY_SCHEDULE_CRON_FILE" 2>/dev/null || true
  fi
}

schedule_remove_units() {
  if command -v systemctl >/dev/null 2>&1; then
    systemctl disable --now "${DEPLOY_SCHEDULE_SERVICE}.timer" >/dev/null 2>&1 || true
    rm -f "/etc/systemd/system/${DEPLOY_SCHEDULE_SERVICE}.service" \
          "/etc/systemd/system/${DEPLOY_SCHEDULE_SERVICE}.timer"
    systemctl daemon-reload >/dev/null 2>&1 || true
  fi
  rm -f "$DEPLOY_SCHEDULE_CRON_FILE"
}

schedule_main() {
  require_root "schedule"
  local subcommand="${1:-status}"
  shift || true
  case "${subcommand,,}" in
    run)
      schedule_run_main "$@"
      ;;
    status)
      schedule_load_config
      echo "enabled=${SCHEDULE_ENABLED} mode=${SCHEDULE_MODE:-update-all} calendar=${SCHEDULE_ON_CALENDAR:-<default>}"
      if command -v systemctl >/dev/null 2>&1 \
          && systemctl list-timers --all 2>/dev/null | grep -q "$DEPLOY_SCHEDULE_SERVICE"; then
        echo "systemd timer active"
      elif [[ -f "$DEPLOY_SCHEDULE_CRON_FILE" ]]; then
        echo "cron entry present"
      else
        echo "no schedule installed"
      fi
      ;;
    unschedule)
      schedule_remove_units
      rm -f "$SCHEDULE_CONF_FILE"
      success "$(t schedule.info.removed)"
      ;;
    schedule|enable|disable|*)
      local enable="" mode="" calendar="" include=""
      [[ "${subcommand,,}" == "schedule" ]] && enable=true
      while (($#)); do
        case "$1" in
          --enable) enable=true; shift ;;
          --disable) enable=false; shift ;;
          --mode) mode="${2:-}"; shift 2 ;;
          --at) calendar="${2:-}"; shift 2 ;;
          --include) include="${2:-}"; shift 2 ;;
          *)
            t schedule.usage "$0"
            return 2
            ;;
        esac
      done
      schedule_load_config
      case "${mode,,}" in
        ""|update-all|check-only) : ;;
        *) error "$(t common.invalid_choice "$mode")" ;;
      esac
      [[ -n "$mode" ]] && SCHEDULE_MODE="${mode,,}"
      [[ -n "$calendar" ]] && SCHEDULE_ON_CALENDAR="$calendar"
      [[ -n "$include" ]] && SCHEDULE_INCLUDE="$include"
      [[ -n "$enable" ]] && SCHEDULE_ENABLED="$( [[ "$enable" == true ]] && echo true || echo false )"
      if ! atomic_write_file "$SCHEDULE_CONF_FILE" 600 <<CONF
SCHEDULE_ENABLED="${SCHEDULE_ENABLED}"
SCHEDULE_MODE="${SCHEDULE_MODE}"
SCHEDULE_ON_CALENDAR="${SCHEDULE_ON_CALENDAR}"
SCHEDULE_INCLUDE="${SCHEDULE_INCLUDE}"
CONF
      then
        error "$(t error.config_write "$SCHEDULE_CONF_FILE")"
      fi
      if [[ "${SCHEDULE_ENABLED,,}" == true ]]; then
        schedule_write_runner || error "$(t error.config_write "$DEPLOY_SCHEDULE_RUNNER")"
        schedule_apply "${SCHEDULE_ON_CALENDAR:-$( [[ "${SCHEDULE_MODE}" == check-only ]] && echo 'Mon..Fri *-*-* 09:00' || echo '*-*-* 04:30' )}" \
          || error "$(t error.config_write "$DEPLOY_SCHEDULE_SERVICE")"
      else
        schedule_remove_units
      fi
      success "$(t schedule.info.saved)"
      ;;
  esac
}
