#!/usr/bin/env bash

# Scheduled update/check runs: `deploy.sh schedule` writes a systemd
# service+timer pair (or a /etc/cron.d entry on non-systemd systems) that
# invokes the runner script; `deploy.sh unschedule` removes both. The runner
# takes the same manager lock as interactive batches, so scheduled and manual
# runs can never overlap, and reports its result through notify_send.
#
# Config lives in /etc/deploy-schedule.conf (root:600):
#   SCHEDULE_ENABLED=true|false
#   SCHEDULE_MODE=update-all|check-only
#   SCHEDULE_ON_CALENDAR=  systemd OnCalendar spec (default daily 04:30)
#   SCHEDULE_INCLUDE=      optional --include list passed to the batch command

SCHEDULE_CONF_FILE="${SCHEDULE_CONF_FILE:-/etc/deploy-schedule.conf}"
DEPLOY_SCHEDULE_SERVICE="${DEPLOY_SCHEDULE_SERVICE:-deploy-scripts-batch}"
DEPLOY_SCHEDULE_CRON_FILE="${DEPLOY_SCHEDULE_CRON_FILE:-/etc/cron.d/deploy-scripts-batch}"
DEPLOY_SCHEDULE_RUNNER="${DEPLOY_SCHEDULE_RUNNER:-/usr/local/bin/deploy-scripts-batch-runner}"

# Retry knob for scheduled batches: how many times a failed run is retried
# (default 0 = fire once), and the base backoff in seconds between attempts
# (doubled each retry, capped at 900).
SCHEDULE_RETRIES="${SCHEDULE_RETRIES:-0}"
SCHEDULE_RETRY_BACKOFF="${SCHEDULE_RETRY_BACKOFF:-300}"

schedule_load_config() {
  local conf_file="$SCHEDULE_CONF_FILE"
  SCHEDULE_ENABLED=false SCHEDULE_MODE="update-all" SCHEDULE_ON_CALENDAR="" SCHEDULE_INCLUDE=""
  [[ -f "$conf_file" ]] || return 0
  # Same trust gate as app and notification configs: root-owned, mode
  # 600/400, or the file is ignored entirely. A world-writable schedule
  # file could otherwise inject --include tokens into the batch command.
  if ! app_conf_trusted_value "$conf_file" "SCHEDULE_ENABLED" >/dev/null 2>&1; then
    return 1
  fi
  local line key value
  while IFS= read -r line; do
    [[ "$line" =~ ^[A-Z_]+= ]] || continue
    key="${line%%=*}"
    value="${line#*=}"
    value="${value%\"}"
    value="${value#\"}"
    case "$key" in
      SCHEDULE_ENABLED|SCHEDULE_MODE|SCHEDULE_ON_CALENDAR|SCHEDULE_INCLUDE|SCHEDULE_RETRIES|SCHEDULE_RETRY_BACKOFF)
        printf -v "$key" '%s' "$value"
        ;;
    esac
  done < "$conf_file"
}

# The script invoked by systemd/cron. Takes the manager lock (fd8, shared
# with interactive batches), runs the configured batch, and lets the batch's
# own notification report the outcome. DEPLOY_NOTIFY_SUPPRESS is NOT set —
# scheduled runs are exactly when notifications matter most.
schedule_write_runner() {
  local runner="$DEPLOY_SCHEDULE_RUNNER"
  local root_dir_literal
  printf -v root_dir_literal '%q' "$DEPLOY_ROOT_DIR"
  if ! atomic_write_file "$runner" 750 <<RUNNER
#!/bin/bash
# Auto-generated by deploy.sh schedule. Do not edit manually.
set -euo pipefail
umask 077
exec bash ${root_dir_literal}/deploy.sh schedule-run
RUNNER
  then
    return 1
  fi
}

# Internal action executed by the runner. Reuses the manager lock so a
# concurrent interactive update-all/backup-all makes this run skip cleanly.
# Failed batches are retried SCHEDULE_RETRIES times with exponential backoff
# (base SCHEDULE_RETRY_BACKOFF, doubled per attempt, capped at 900s) before
# the run finally reports failure through the notification path.
schedule_run_main() {
  require_root "schedule-run"
  schedule_load_config || true
  [[ "${SCHEDULE_ENABLED,,}" == true ]] || { echo "scheduled batch disabled; nothing to do." >&2; return 0; }
  local include_args=()
  if [[ -n "${SCHEDULE_INCLUDE:-}" ]]; then
    read -r -a include_args <<< "--include $SCHEDULE_INCLUDE"
  fi
  local mode="${SCHEDULE_MODE:-update-all}" batch_cmd attempt=0 max_attempts backoff status=0
  case "$mode" in
    check-only) batch_cmd="check-update" ;;
    update-all) batch_cmd="update-all" ;;
    *)
      echo "unknown schedule mode: $SCHEDULE_MODE" >&2
      return 2
      ;;
  esac
  [[ "$SCHEDULE_RETRIES" =~ ^[0-9]+$ ]] || SCHEDULE_RETRIES=0
  [[ "$SCHEDULE_RETRY_BACKOFF" =~ ^[0-9]+$ ]] || SCHEDULE_RETRY_BACKOFF=300
  backoff="$SCHEDULE_RETRY_BACKOFF"
  max_attempts=$(( SCHEDULE_RETRIES + 1 ))
  while (( attempt < max_attempts )); do
    if bash "$DEPLOY_ROOT_DIR/deploy.sh" "$batch_cmd" \
        ${include_args[@]+"${include_args[@]}"}; then
      return 0
    fi
    status=$?
    attempt=$((attempt + 1))
    if (( attempt < max_attempts )); then
      warn "$(t schedule.warn.retry "$status" "$attempt" "$max_attempts")"
      sleep "$backoff"
      backoff=$(( backoff * 2 ))
      (( backoff > 900 )) && backoff=900
    fi
  done
  return "$status"
}

# Validate a schedule specification before it reaches the unit files. On
# systemd systems the authoritative check is `systemd-analyze calendar`;
# when that tool is unavailable (or the spec is a plain HH:MM used by the
# cron fallback) we fall back to a conservative shape check so a typo fails
# loudly at `schedule` time instead of silently producing a never-firing
# timer.
schedule_validate_calendar() {
  local calendar="$1"
  if [[ "$calendar" =~ ^([0-9]+):([0-9]+)$ ]]; then
    local hour minute
    hour="$((10#${BASH_REMATCH[1]}))"
    minute="$((10#${BASH_REMATCH[2]}))"
    [[ "$hour" -le 23 && "$minute" -le 59 ]] || {
      echo "Invalid schedule specification: $calendar" >&2
      return 2
    }
    return 0
  fi
  if command -v systemd-analyze >/dev/null 2>&1; then
    if systemd-analyze calendar "$calendar" >/dev/null 2>&1; then
      return 0
    fi
    echo "Invalid OnCalendar specification: $calendar" >&2
    return 2
  fi
  # Conservative shape check without systemd-analyze: allow word-ish and
  # *-* date/time patterns, but reject whitespace-padded or obviously broken
  # values that would otherwise fail only when the timer is loaded.
  if [[ "$calendar" =~ ^[^[:space:]]+(.*[^[:space:]])?$ ]] \
      && [[ "$calendar" == *"/"* || "$calendar" == *:* || "$calendar" == *"-"* || "$calendar" == "*"* ]]; then
    return 0
  fi
  echo "Invalid schedule specification: $calendar" >&2
  return 2
}

# Write or refresh the scheduling units. Prefers systemd timers; falls back
# to /etc/cron.d where systemd is unavailable.
schedule_apply() {
  local calendar="$1"
  schedule_validate_calendar "$calendar" || return 2
  if command -v systemctl >/dev/null 2>&1 && systemctl is-system-running >/dev/null 2>&1; then
    local service_file="/etc/systemd/system/${DEPLOY_SCHEDULE_SERVICE}.service"
    local timer_file="/etc/systemd/system/${DEPLOY_SCHEDULE_SERVICE}.timer"
    atomic_write_file "$service_file" 644 <<SERVICE \
      || return 1
[Unit]
Description=deploy-scripts scheduled batch (update-all / check-update)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=${DEPLOY_SCHEDULE_RUNNER}
SERVICE
    atomic_write_file "$timer_file" 644 <<TIMER || return 1
[Unit]
Description=Run deploy-scripts scheduled batch

[Timer]
OnCalendar=${calendar}
Persistent=true

[Install]
WantedBy=timers.target
TIMER
    systemctl daemon-reload || return 1
    systemctl enable --now "${DEPLOY_SCHEDULE_SERVICE}.timer" >/dev/null 2>&1 || return 1
  else
    local cron_spec="${calendar}"
    # Convert the common daily "HH:MM" systemd form to cron; anything more
    # exotic must already be a valid 5-field crontab expression.
    if [[ "$calendar" =~ ^([0-9]+):([0-9]+)$ ]]; then
      cron_spec="$((10#${BASH_REMATCH[2]})) $((10#${BASH_REMATCH[1]})) * * *"
    fi
    if ! [[ "$cron_spec" =~ ^[0-9*,-/]+[[:space:]]+[0-9*,-/]+[[:space:]]+[0-9*,-/]+[[:space:]]+[0-9*,-/]+[[:space:]]+[0-9*,-/]+$ ]]; then
      echo "Invalid schedule specification: $calendar" >&2
      return 2
    fi
    atomic_write_file "$DEPLOY_SCHEDULE_CRON_FILE" 644 <<CRON || return 1
# Auto-generated by deploy.sh schedule. Do not edit manually.
${cron_spec} root ${DEPLOY_SCHEDULE_RUNNER}
CRON
    chmod 644 "$DEPLOY_SCHEDULE_CRON_FILE" 2>/dev/null || true
  fi
}

schedule_remove_units() {
  if command -v systemctl >/dev/null 2>&1; then
    systemctl disable --now "${DEPLOY_SCHEDULE_SERVICE}.timer" >/dev/null 2>&1 || true
    rm -f "/etc/systemd/system/${DEPLOY_SCHEDULE_SERVICE}.service" \
          "/etc/systemd/system/${DEPLOY_SCHEDULE_SERVICE}.timer"
    systemctl daemon-reload >/dev/null 2>&1 || true
  fi
  rm -f "$DEPLOY_SCHEDULE_CRON_FILE"
}

schedule_main() {
  require_root "schedule"
  local subcommand="${1:-status}"
  shift || true
  case "${subcommand,,}" in
    run|schedule-run)
      schedule_run_main "$@"
      return $?
      ;;
    status)
      schedule_load_config || true
      echo "enabled=${SCHEDULE_ENABLED} mode=${SCHEDULE_MODE:-update-all} calendar=${SCHEDULE_ON_CALENDAR:-<default>}"
      if command -v systemctl >/dev/null 2>&1 \
          && systemctl list-timers --all 2>/dev/null | grep -q "$DEPLOY_SCHEDULE_SERVICE"; then
        echo "systemd timer active"
      elif [[ -f "$DEPLOY_SCHEDULE_CRON_FILE" ]]; then
        echo "cron entry present"
      else
        echo "no schedule installed"
      fi
      ;;
    unschedule)
      schedule_remove_units
      rm -f "$SCHEDULE_CONF_FILE"
      success "$(t schedule.info.removed)"
      ;;
    schedule|enable|disable|*)
      local enable="" mode="" calendar="" include="" retries="" backoff=""
      [[ "${subcommand,,}" == "schedule" ]] && enable=true
      while (($#)); do
        case "$1" in
          --enable) enable=true; shift ;;
          --disable) enable=false; shift ;;
          --mode) mode="${2:-}"; shift 2 ;;
          --at) calendar="${2:-}"; shift 2 ;;
          --include) include="${2:-}"; shift 2 ;;
          --retries) retries="${2:-}"; shift 2 ;;
          --backoff) backoff="${2:-}"; shift 2 ;;
          *)
            t schedule.usage "$0"
            return 2
            ;;
        esac
      done
      schedule_load_config || true
      case "${mode,,}" in
        ""|update-all|check-only) : ;;
        *) error "$(t common.invalid_choice "$mode")" ;;
      esac
      [[ -n "$mode" ]] && SCHEDULE_MODE="${mode,,}"
      [[ -n "$calendar" ]] && SCHEDULE_ON_CALENDAR="$calendar"
      [[ -n "$include" ]] && SCHEDULE_INCLUDE="$include"
      if [[ -n "${retries:-}" ]]; then
        [[ "$retries" =~ ^[0-9]+$ ]] || error "$(t common.invalid_choice "$retries")"
        SCHEDULE_RETRIES="$retries"
      fi
      if [[ -n "${backoff:-}" ]]; then
        [[ "$backoff" =~ ^[0-9]+$ ]] || error "$(t common.invalid_choice "$backoff")"
        SCHEDULE_RETRY_BACKOFF="$backoff"
      fi
      [[ -n "$enable" ]] && SCHEDULE_ENABLED="$( [[ "$enable" == true ]] && echo true || echo false )"
      # Validate an explicit calendar before persisting it, so a typo can
      # never leave a broken value in the config file.
      if [[ -n "${SCHEDULE_ON_CALENDAR:-}" ]]; then
        schedule_validate_calendar "$SCHEDULE_ON_CALENDAR" || return 2
      fi
      if ! atomic_write_file "$SCHEDULE_CONF_FILE" 600 <<CONF
SCHEDULE_ENABLED="${SCHEDULE_ENABLED}"
SCHEDULE_MODE="${SCHEDULE_MODE}"
SCHEDULE_ON_CALENDAR="${SCHEDULE_ON_CALENDAR}"
SCHEDULE_INCLUDE="${SCHEDULE_INCLUDE}"
SCHEDULE_RETRIES="${SCHEDULE_RETRIES}"
SCHEDULE_RETRY_BACKOFF="${SCHEDULE_RETRY_BACKOFF}"
CONF
      then
        error "$(t error.config_write "$SCHEDULE_CONF_FILE")"
      fi
      if [[ "${SCHEDULE_ENABLED,,}" == true ]]; then
        schedule_write_runner || error "$(t error.config_write "$DEPLOY_SCHEDULE_RUNNER")"
        # schedule_apply reports its own diagnostics (invalid calendar, unit
        # write failure); a non-zero return is enough to abort the command.
        schedule_apply "${SCHEDULE_ON_CALENDAR:-$( [[ "${SCHEDULE_MODE}" == check-only ]] && echo 'Mon..Fri *-*-* 09:00' || echo '*-*-* 04:30' )}" \
          || return 1
      else
        schedule_remove_units
      fi
      success "$(t schedule.info.saved)"
      ;;
  esac
}
