#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="${ROOT_DIR}/dist"

usage() {
  echo "Usage: bash tools/build-release.sh [all|newapi|sub2api|vaultwarden|cyberstrikeai|blog]" >&2
}

app_file_for() {
  case "$1" in
    newapi) echo "apps/newapi.sh" ;;
    sub2api) echo "apps/sub2api.sh" ;;
    vaultwarden) echo "apps/vaultwarden.sh" ;;
    cyberstrikeai) echo "apps/cyberstrikeai.sh" ;;
    blog) echo "apps/blog.sh" ;;
    *) return 1 ;;
  esac
}

impl_file_for() {
  case "$1" in
    newapi) echo "impl/install_newapi.sh" ;;
    sub2api) echo "impl/install_sub2api.sh" ;;
    vaultwarden) echo "impl/install_vaultwarden.sh" ;;
    cyberstrikeai) echo "impl/install_cyberstrikeai.sh" ;;
    blog) echo "impl/install_blog.sh" ;;
    *) return 1 ;;
  esac
}

emit_without_shebang() {
  local file="$1"
  awk 'NR == 1 && /^#!/ { next } { print }' "$file"
}

build_one() {
  local app="$1"
  local app_file impl_file output commit built_at
  app_file="$(app_file_for "$app")" || {
    usage
    exit 1
  }
  impl_file="$(impl_file_for "$app")" || {
    usage
    exit 1
  }
  output="${DIST_DIR}/install_${app}.sh"
  commit="${DEPLOY_BUILD_COMMIT:-$(git -C "$ROOT_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)}"
  built_at="${SOURCE_DATE_EPOCH:-}"
  if [[ -n "$built_at" ]]; then
    built_at="$(date -u -d "@${built_at}" '+%Y-%m-%dT%H:%M:%SZ')"
  else
    built_at="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  fi

  mkdir -p "$DIST_DIR"
  {
    echo '#!/usr/bin/env bash'
    echo 'set -euo pipefail'
    echo
    echo "# Generated by tools/build-release.sh at ${built_at} from commit ${commit}."
    echo '# Edit source files under lib/ and apps/, then rebuild this file.'
    echo
    echo 'DEPLOY_BUNDLED=1'
    echo 'DEPLOY_ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"'
    echo
    echo '# ----- lib/i18n.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/i18n.sh"
    echo
    echo '# ----- lib/logging.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/logging.sh"
    echo
    echo '# ----- lib/fs.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/fs.sh"
    echo
    echo '# ----- lib/lock.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/lock.sh"
    echo
    echo '# ----- lib/config.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/config.sh"
    echo
    echo '# ----- lib/service.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/service.sh"
    echo
    echo '# ----- lib/network.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/network.sh"
    echo
    echo '# ----- lib/app_loader.sh -----'
    echo "BUNDLED_APP_IMPL_SCRIPT_NAME=\"install_${app}_impl.sh\""
    emit_without_shebang "${ROOT_DIR}/lib/app_loader.sh"
    echo
    echo '# ----- lib/cli.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/cli.sh"
    echo
    echo 'main() {'
    echo '  dispatch_action "${1:-menu}"'
    echo '}'
    echo
    echo '# ----- app definition -----'
    emit_without_shebang "${ROOT_DIR}/${app_file}"
    echo
    echo 'main "$@"'
    echo 'exit 0'
    echo '__DEPLOY_APP_IMPL_SCRIPT__'
    cat "${ROOT_DIR}/${impl_file}"
  } > "$output"

  chmod 755 "$output"
  echo "Built ${output}"
}

main() {
  local target="${1:-all}"
  case "$target" in
    all)
      build_one newapi
      build_one sub2api
      build_one vaultwarden
      build_one cyberstrikeai
      build_one blog
      ;;
    newapi|sub2api|vaultwarden|cyberstrikeai|blog)
      build_one "$target"
      ;;
    *)
      usage
      exit 1
      ;;
  esac
}

main "$@"
