#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="${ROOT_DIR}/dist"

source "${ROOT_DIR}/lib/app_registry.sh"

usage() {
  echo "Usage: bash tools/build-release.sh [all|manager|$(deploy_app_ids | paste -sd '|')]" >&2
}

fail() {
  echo "build-release: $*" >&2
  exit 1
}

emit_without_shebang() {
  local file="$1"
  awk 'NR == 1 && /^#!/ { next } { print }' "$file"
}

build_one() {
  local app="$1"
  local app_file impl_file output output_tmp commit built_at
  output_tmp=""
  app_file="$(deploy_app_file_for "$app")" || {
    usage
    exit 1
  }
  impl_file="$(deploy_app_impl_file_for "$app")" || {
    usage
    exit 1
  }
  output="${DIST_DIR}/install_${app}.sh"
  commit="${DEPLOY_BUILD_COMMIT:-$(git -C "$ROOT_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)}"
  built_at="${SOURCE_DATE_EPOCH:-}"
  if [[ -n "$built_at" ]]; then
    built_at="$(date -u -d "@${built_at}" '+%Y-%m-%dT%H:%M:%SZ')"
  else
    built_at="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  fi

  if ! mkdir -p "$DIST_DIR"; then
    fail "cannot create output directory: ${DIST_DIR}"
  fi
  if ! output_tmp="$(mktemp "${output}.XXXXXX")"; then
    fail "cannot create temporary output for ${output}"
  fi
  if ! {
    echo '#!/usr/bin/env bash'
    echo 'set -euo pipefail'
    echo
    echo "# Generated by tools/build-release.sh at ${built_at} from commit ${commit}."
    echo '# Edit source files under lib/ and apps/, then rebuild this file.'
    echo
    echo 'DEPLOY_BUNDLED=1'
    echo 'DEPLOY_ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"'
    echo
    echo '# ----- lib/i18n.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/i18n.sh"
    echo
    echo '# ----- lib/logging.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/logging.sh"
    echo
    echo '# ----- lib/fs.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/fs.sh"
    echo
    echo '# ----- lib/atomic.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/atomic.sh"
    echo
    echo '# ----- lib/binary.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/binary.sh"
    echo
    echo '# ----- lib/lock.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/lock.sh"
    echo
    echo '# ----- lib/config.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/config.sh"
    echo
    echo '# ----- lib/service.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/service.sh"
    echo
    echo '# ----- lib/network.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/network.sh"
    echo
    echo '# ----- lib/app.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/app.sh"
    echo
    echo '# ----- lib/app_loader.sh -----'
    echo "BUNDLED_APP_IMPL_SCRIPT_NAME=\"install_${app}_impl.sh\""
    emit_without_shebang "${ROOT_DIR}/lib/app_loader.sh"
    echo
    echo '# ----- lib/cli.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/cli.sh"
    echo
    echo 'main() {'
    echo '  dispatch_action "${1:-menu}"'
    echo '}'
    echo
    echo '# ----- app definition -----'
    emit_without_shebang "${ROOT_DIR}/${app_file}"
    echo
    echo 'main "$@"'
    echo 'exit 0'
    echo '__DEPLOY_APP_IMPL_SCRIPT__'
    cat "${ROOT_DIR}/${impl_file}"
  } > "$output_tmp"; then
    rm -f "$output_tmp"
    fail "failed to compose release script for ${app}: ${output}"
  fi

  if ! chmod 755 "$output_tmp" || ! mv "$output_tmp" "$output"; then
    rm -f "$output_tmp"
    fail "failed to install release script: ${output}"
  fi
  echo "Built ${output}"
}

build_manager() {
  local output output_tmp commit built_at app app_file impl_file
  output="${DIST_DIR}/deploy.sh"
  output_tmp=""
  commit="${DEPLOY_BUILD_COMMIT:-$(git -C "$ROOT_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)}"
  built_at="${SOURCE_DATE_EPOCH:-}"
  if [[ -n "$built_at" ]]; then
    built_at="$(date -u -d "@${built_at}" '+%Y-%m-%dT%H:%M:%SZ')"
  else
    built_at="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  fi

  if ! mkdir -p "$DIST_DIR"; then
    fail "cannot create output directory: ${DIST_DIR}"
  fi
  if ! output_tmp="$(mktemp "${output}.XXXXXX")"; then
    fail "cannot create temporary output for ${output}"
  fi
  if ! {
    echo '#!/usr/bin/env bash'
    echo 'set -euo pipefail'
    echo
    echo "# Generated by tools/build-release.sh at ${built_at} from commit ${commit}."
    echo '# Edit source files under lib/ and apps/, then rebuild this file.'
    echo
    echo 'DEPLOY_BUNDLED=1'
    echo 'DEPLOY_BUNDLED_MANAGER=1'
    echo 'DEPLOY_ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"'
    echo
    echo '# ----- lib/i18n.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/i18n.sh"
    echo
    echo '# ----- lib/logging.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/logging.sh"
    echo
    echo '# ----- lib/fs.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/fs.sh"
    echo
    echo '# ----- lib/atomic.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/atomic.sh"
    echo
    echo '# ----- lib/binary.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/binary.sh"
    echo
    echo '# ----- lib/lock.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/lock.sh"
    echo
    echo '# ----- lib/config.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/config.sh"
    echo
    echo '# ----- lib/service.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/service.sh"
    echo
    echo '# ----- lib/network.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/network.sh"
    echo
    echo '# ----- lib/app.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/app.sh"
    echo
    echo '# ----- lib/app_registry.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/app_registry.sh"
    echo
    echo '# ----- lib/app_loader.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/app_loader.sh"
    echo
    echo '# ----- lib/cli.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/cli.sh"
    echo
    echo '# ----- lib/manager_cli.sh -----'
    emit_without_shebang "${ROOT_DIR}/lib/manager_cli.sh"
    echo
    echo 'manager_main "$@"'
    echo 'exit 0'
    for app in "${DEPLOY_APP_IDS[@]}"; do
      app_file="$(deploy_app_file_for "$app")"
      echo
      echo "__DEPLOY_APP_DEFINITION__ ${app}"
      emit_without_shebang "${ROOT_DIR}/${app_file}"
      echo "__DEPLOY_APP_DEFINITION_END__"
    done
    for app in "${DEPLOY_APP_IDS[@]}"; do
      impl_file="$(deploy_app_impl_file_for "$app")"
      echo
      echo "__DEPLOY_APP_IMPL_SCRIPT__ install_${app}_impl.sh"
      cat "${ROOT_DIR}/${impl_file}"
      echo "__DEPLOY_APP_IMPL_SCRIPT_END__"
    done
  } > "$output_tmp"; then
    rm -f "$output_tmp"
    fail "failed to compose release script for manager: ${output}"
  fi

  if ! chmod 755 "$output_tmp" || ! mv "$output_tmp" "$output"; then
    rm -f "$output_tmp"
    fail "failed to install release script: ${output}"
  fi
  echo "Built ${output}"
}

main() {
  local target="${1:-all}"
  case "$target" in
    all)
      local app
      for app in "${DEPLOY_APP_IDS[@]}"; do
        build_one "$app"
      done
      build_manager
      ;;
    manager)
      build_manager
      ;;
    *)
      if deploy_app_file_for "$target" >/dev/null 2>&1; then
        build_one "$target"
        return 0
      fi
      usage
      exit 1
      ;;
  esac
}

main "$@"
