#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="${ROOT_DIR}/dist"

COMMON_RELEASE_LIB_FILES=(
  lib/i18n.sh
  lib/logging.sh
  lib/fs.sh
  lib/atomic.sh
  lib/binary.sh
  lib/lock.sh
  lib/config.sh
  lib/service.sh
  lib/network.sh
  lib/version.sh
  lib/operation.sh
  lib/state.sh
  lib/manager_status.sh
  lib/manager_history.sh
  lib/manager_doctor.sh
  lib/manager_backup.sh
  lib/app.sh
  lib/binary_app.sh
)

source "${ROOT_DIR}/lib/app_registry.sh"

usage() {
  echo "Usage: bash tools/build-release.sh [all|manager|$(deploy_app_ids | paste -sd '|')]" >&2
}

fail() {
  echo "build-release: $*" >&2
  exit 1
}

emit_without_shebang() {
  local file="$1"
  awk 'NR == 1 && /^#!/ { next } { print }' "$file"
}

emit_release_header() {
  local commit="$1" built_at="$2"
  echo '#!/usr/bin/env bash'
  echo 'set -euo pipefail'
  echo
  echo "# Generated by tools/build-release.sh at ${built_at} from commit ${commit}."
  echo '# Edit source files under lib/ and apps/, then rebuild this file.'
  echo
}

emit_release_files() {
  local file
  for file in "$@"; do
    echo "# ----- ${file} -----"
    emit_without_shebang "${ROOT_DIR}/${file}"
    echo
  done
}

emit_common_release_libs() {
  emit_release_files "${COMMON_RELEASE_LIB_FILES[@]}"
}

emit_app_loader_file() {
  local app="${1:-}"
  echo '# ----- lib/app_loader.sh -----'
  if [[ -n "$app" ]]; then
    printf 'BUNDLED_APP_IMPL_SCRIPT_NAME="%s"\n' "$(deploy_app_bundled_impl_script_name_for "$app")"
  fi
  emit_without_shebang "${ROOT_DIR}/lib/app_loader.sh"
  echo
}

emit_app_definition() {
  local app_file="$1"
  echo '# ----- app definition -----'
  emit_without_shebang "${ROOT_DIR}/${app_file}"
  echo
}

emit_manager_app_definitions() {
  local app app_file
  for app in "${DEPLOY_APP_IDS[@]}"; do
    app_file="$(deploy_app_file_for "$app")"
    echo
    echo "__DEPLOY_APP_DEFINITION__ ${app}"
    emit_without_shebang "${ROOT_DIR}/${app_file}"
    echo "__DEPLOY_APP_DEFINITION_END__"
  done
}

emit_app_impl_payload() {
  local impl_file="$1"
  echo '__DEPLOY_APP_IMPL_SCRIPT__'
  cat "${ROOT_DIR}/${impl_file}"
}

emit_manager_app_impl_payloads() {
  local app impl_file
  for app in "${DEPLOY_APP_IDS[@]}"; do
    impl_file="$(deploy_app_impl_file_for "$app")"
    echo
    echo "__DEPLOY_APP_IMPL_SCRIPT__ $(deploy_app_bundled_impl_script_name_for "$app")"
    cat "${ROOT_DIR}/${impl_file}"
    echo "__DEPLOY_APP_IMPL_SCRIPT_END__"
  done
}

release_build_commit() {
  printf '%s\n' "${DEPLOY_BUILD_COMMIT:-$(git -C "$ROOT_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)}"
}

release_built_at() {
  local built_at="${SOURCE_DATE_EPOCH:-}"
  if [[ -n "$built_at" ]]; then
    date -u -d "@${built_at}" '+%Y-%m-%dT%H:%M:%SZ'
  else
    date -u '+%Y-%m-%dT%H:%M:%SZ'
  fi
}

prepare_output_file() {
  local output="$1" output_tmp
  if ! mkdir -p "$DIST_DIR"; then
    fail "cannot create output directory: ${DIST_DIR}"
  fi
  if ! output_tmp="$(mktemp "${output}.XXXXXX")"; then
    fail "cannot create temporary output for ${output}"
  fi
  printf '%s\n' "$output_tmp"
}

install_output_file() {
  local output_tmp="$1" output="$2"
  if ! chmod 755 "$output_tmp" || ! mv "$output_tmp" "$output"; then
    rm -f "$output_tmp"
    fail "failed to install release script: ${output}"
  fi
}

build_one() {
  local app="$1"
  local app_file impl_file output output_tmp commit built_at
  app_file="$(deploy_app_file_for "$app")" || {
    usage
    exit 1
  }
  impl_file="$(deploy_app_impl_file_for "$app")" || {
    usage
    exit 1
  }
  output="${DIST_DIR}/$(deploy_app_script_name_for "$app")"
  output_tmp="$(prepare_output_file "$output")"
  commit="$(release_build_commit)"
  built_at="$(release_built_at)"

  if ! {
    emit_release_header "$commit" "$built_at"
    echo 'DEPLOY_BUNDLED=1'
    echo 'DEPLOY_ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"'
    echo
    emit_common_release_libs
    emit_app_loader_file "$app"
    emit_release_files lib/cli.sh
    echo 'main() {'
    echo '  dispatch_action "${1:-menu}"'
    echo '}'
    echo
    emit_app_definition "$app_file"
    echo 'main "$@"'
    echo 'exit 0'
    emit_app_impl_payload "$impl_file"
  } > "$output_tmp"; then
    rm -f "$output_tmp"
    fail "failed to compose release script for ${app}: ${output}"
  fi

  install_output_file "$output_tmp" "$output"
  echo "Built ${output}"
}

build_manager() {
  local output output_tmp commit built_at
  output="${DIST_DIR}/deploy.sh"
  output_tmp="$(prepare_output_file "$output")"
  commit="$(release_build_commit)"
  built_at="$(release_built_at)"

  if ! {
    emit_release_header "$commit" "$built_at"
    echo 'DEPLOY_BUNDLED=1'
    echo 'DEPLOY_BUNDLED_MANAGER=1'
    echo 'DEPLOY_ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"'
    echo
    emit_common_release_libs
    emit_release_files lib/app_registry.sh
    emit_app_loader_file
    emit_release_files lib/cli.sh lib/manager_cli.sh
    echo 'manager_main "$@"'
    echo 'exit 0'
    emit_manager_app_definitions
    emit_manager_app_impl_payloads
  } > "$output_tmp"; then
    rm -f "$output_tmp"
    fail "failed to compose release script for manager: ${output}"
  fi

  install_output_file "$output_tmp" "$output"
  echo "Built ${output}"
}

main() {
  local target="${1:-all}"
  case "$target" in
    all)
      local app
      for app in "${DEPLOY_APP_IDS[@]}"; do
        build_one "$app"
      done
      build_manager
      ;;
    manager)
      build_manager
      ;;
    *)
      if deploy_app_file_for "$target" >/dev/null 2>&1; then
        build_one "$target"
        return 0
      fi
      usage
      exit 1
      ;;
  esac
}

main "$@"
